name: Push components to Espressif Component Service

on:
  workflow_dispatch:

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "esp-ml307: ."
          namespace: "78"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
